---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: flake8
      - id: debug-statements
      - id: check-docstring-first
